# Generated by Django 5.2.1 on 2025-06-07 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('crypto', 'Криптовалюта'),
                            ('stock', 'Акции'),
                            ('bond', 'Облигации'),
                            ('currency', 'Валюта'),
                        ],
                        max_length=32,
                    ),
                ),
                ('ticker', models.CharField(max_length=10)),
                ('isin', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[],
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01T00:00:00Z'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], max_length=5)),
                ('type', models.CharField(choices=[('market', 'Рыночная'), ('limit', 'Лимитная')], max_length=32)),
                ('price', models.FloatField(blank=True, null=True)),
                ('tool_quantity', models.IntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('open', 'Открыта'),
                            ('partially_filled', 'Частично исполнена'),
                            ('filled', 'Исполнена'),
                            ('cancelled', 'Отменена'),
                            ('rejected', 'Отклонена'),
                        ],
                        max_length=32,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('filled', models.IntegerField(blank=True, null=True)),
                (
                    'user_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                ('tool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tool')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                (
                    'ask_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asks', to='app.order'),
                ),
                (
                    'bid_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='app.order'),
                ),
                (
                    'buyer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='buy_trades',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'seller',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sell_trades',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('tool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tool')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
            },
        ),
        migrations.CreateModel(
            name='UserTool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserTool',
                'verbose_name_plural': 'UserTools',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tools',
            field=models.ManyToManyField(related_name='users', through='app.UserTool', to='app.tool'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='balances',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'tool',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='app.tool'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
                'unique_together': {('user', 'tool')},
            },
        ),
        migrations.AddConstraint(
            model_name='usertool',
            constraint=models.UniqueConstraint(fields=('user', 'tool'), name='unique_user_tool'),
        ),
    ]
