# Generated by Django 5.2.1 on 2025-06-11 18:49
from django.conf import settings
from django.db import migrations


def create_base_tool(apps, schema_editor):
    Tool = apps.get_model('app', 'Tool')

    if not Tool.objects.filter(name=settings.BASE_NAME).exists():
        Tool.objects.create(
            name=settings.BASE_NAME,
            type=settings.BASE_TYPE,
            ticker=settings.BASE_TICKER,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_base_tool),
    ]
