# Generated by Django 5.2.3 on 2025-06-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_create_base_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='reserved_amount',
            field=models.IntegerField(default=0),
        ),
    ]
