FROM alpine:3.18

RUN apk add --no-cache \
    ca-certificates \
    gettext \
    curl \
    tar

ENV ALERTMANAGER_VERSION=0.29.0

RUN curl -L -o /tmp/alertmanager.tar.gz \
    https://github.com/prometheus/alertmanager/releases/download/v${ALERTMANAGER_VERSION}/alertmanager-${ALERTMANAGER_VERSION}.linux-amd64.tar.gz && \
    tar -xzf /tmp/alertmanager.tar.gz -C /tmp && \
    mv /tmp/alertmanager-${ALERTMANAGER_VERSION}.linux-amd64/alertmanager /bin/alertmanager && \
    mv /tmp/alertmanager-${ALERTMANAGER_VERSION}.linux-amd64/amtool /bin/amtool && \
    rm -rf /tmp/*

COPY alertmanager.yml.template /etc/alertmanager/alertmanager.yml.template
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
